apiVersion: v1
kind: Service
metadata:
  name: herbarium-databots
  namespace: databots
  labels:
    app: herbarium-databots
spec:
  type: ClusterIP
  selector:
    app: herbarium-databots
  ports:
    - name: http
      port: 5000
      targetPort: http
